spring.application.name=pam-backend

spring.datasource.url=jdbc:mysql://localhost:3306/pam_database
spring.datasource.username=root
spring.datasource.password=varun1217

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true