import React,{useState,useEffect,useCallback} from 'react';
import {createRoot} from 'react-dom/client';
import {can,canAdmin,allowedApps,destination} from './access.js';
import './style.css';
const apps={HR:{name:'Human resources',icon:'people',description:'Your people workspace, protected by your identity.'},ATTENDANCE:{name:'Attendance',icon:'calendar',description:'A simple workspace to demonstrate attendance access.'},INVENTORY:{name:'Inventory',icon:'box',description:'Resource access with clear management permissions.'}};
const paths={shield:<><path d="m12 3 8 3v6c0 5-8 9-8 9s-8-4-8-9V6z"/><path d="m8 12 3 3 5-6"/></>,grid:<><rect x="3" y="3" width="7" height="7" rx="1"/><rect x="14" y="3" width="7" height="7" rx="1"/><rect x="3" y="14" width="7" height="7" rx="1"/><rect x="14" y="14" width="7" height="7" rx="1"/></>,people:<><circle cx="9" cy="8" r="3"/><path d="M3 21v-3a6 6 0 0 1 12 0v3M16 5a3 3 0 0 1 0 6m2 4a5 5 0 0 1 3 5"/></>,calendar:<><rect x="3" y="5" width="18" height="16" rx="2"/><path d="M7 3v4m10-4v4M3 11h18m-14 5h3m4 0h3"/></>,box:<path d="m12 3 9 5v9l-9 5-9-5V8zM3 8l9 5 9-5M12 13v9M7 5l10 6"/>,key:<><circle cx="8" cy="9" r="5"/><path d="m12 13 8 8m-5-5 3-3m0 6 3-3"/></>,audit:<><rect x="5" y="3" width="14" height="18" rx="2"/><path d="M9 8h6m-6 4h6m-6 4h4"/></>,arrow:<path d="M4 12h16m-6-6 6 6-6 6"/>,check:<path d="m5 12 4 4L19 6"/>};
function Icon({name='shield'}){return <svg width="21" height="21" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{paths[name]||paths.shield}</svg>}
function Brand({inside=false}){return <a className="brand" href={inside?'#dashboard':'#home'}><span><Icon/></span>SafeAccess<b>.</b></a>}
function Badge({children,tone=''}){return <span className={'badge '+tone}>{children}</span>}
function Notice({message}){return message?<div className="notice" role="alert">{message}</div>:null}
function friendlyError(status,message){if(status===401)return 'Email or password is incorrect.';if(status===403)return "You don't have permission to access this resource.";if(status===404)return 'The requested resource could not be found.';if(status>=500)return 'Something went wrong. Please try again.';return message||'The request could not be completed.'}
function Field({label,...props}){return <label className="field"><span>{label}</span><input {...props}/></label>}
function Heading({title,description,action,eyebrow='WORKSPACE'}){return <div className="heading"><div><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{description}</p></div>{action}</div>}
function Loading(){return <div className="loading" role="status"><i/>Loading from PAM Backend…</div>}
function useData(api,path){const [data,setData]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(true);const load=useCallback(async()=>{setBusy(true);setError('');try{setData((await api(path)).data)}catch(e){setError(e.message)}finally{setBusy(false)}},[api,path]);useEffect(()=>{load()},[load]);return {data,error,busy,load};}
function App(){
 const [route,setRoute]=useState(location.hash.slice(1)||'home'),[session,setSession]=useState(null),[challenge,setChallenge]=useState(null),[flash,setFlash]=useState('');
 const go=r=>{location.hash=r;};
 useEffect(()=>{const fn=()=>{setRoute(location.hash.slice(1)||'home');setFlash('');};addEventListener('hashchange',fn);return()=>removeEventListener('hashchange',fn)},[]);
 const api=useCallback(async(path,{method='GET',body,token}={})=>{let r;try{r=await fetch('/api'+path,{method,headers:{...(body?{'Content-Type':'application/json'}:{}),...((token||session?.token)?{Authorization:'Bearer '+(token||session.token)}:{})},body:body?JSON.stringify(body):undefined});}catch{throw Error('Cannot reach PAM Backend. Check that it is running.');}const data=await r.json().catch(()=>({message:'Unexpected response from PAM Backend.'}));if(!r.ok){if(r.status===401&&session){setSession(null);go('login');throw Error('Your session has expired. Please sign in again.');}throw Error(friendlyError(r.status,data.message));}return data;},[session?.token]);
 useEffect(()=>{if(session){const t=setTimeout(()=>{setSession(null);go('login');setFlash('Your session expired. Sign in again.');},Math.max(0,session.expiresAt-Date.now()));return()=>clearTimeout(t)}},[session]);
 const resolved=destination(route,!!session);useEffect(()=>{if(resolved!==route)go(resolved)},[resolved,route]);
 async function verified(result){const me=await api('/auth/me',{token:result.token});setSession({token:result.token,profile:me.data,expiresAt:Date.now()+result.expiresIn*1000});setChallenge(null);go('dashboard');}
 async function refresh(){const me=await api('/auth/me');setSession(s=>s?{...s,profile:me.data}:s);}
 if(!session)return <div className="public"><header className="public-header"><Brand/><nav><a href="#home">Platform</a><a href="#login">Sign in</a><a className="button small" href="#register">Create account <Icon name="arrow"/></a></nav></header>{resolved==='home'?<Landing/>:<div className="auth-layout"><aside className="auth-story"><Badge>IDENTITY, SIMPLIFIED</Badge><h1>One identity.<br/>The right access.</h1><p>Your people and applications, connected through a secure sign-in.</p><div className="steps">{['Password verification','Multi-factor authentication','Permission-based access'].map((s,i)=><div key={s}><span>0{i+1}</span>{s}<Icon name="check"/></div>)}</div><div className="story-foot"><Icon/> SafeAccess identity platform <small>PAM Backend</small></div></aside><Auth key={resolved} route={resolved} api={api} challenge={challenge} setChallenge={setChallenge} go={go} verified={verified} flash={flash}/></div>}<footer className="public-footer"><span>SafeAccess — A Lightweight IAM Platform with SSO and MFA</span><span>Powered by PAM Backend</span></footer></div>;
 const p=session.profile;const nav=[['dashboard','grid','Overview'],...allowedApps(p).map(a=>[a.name.toLowerCase(),apps[a.name]?.icon||'box',apps[a.name]?.name||a.name])];if(canAdmin(p))nav.push(['admin','shield','Administration'],['users','people','Users'],['roles','key','Roles & permissions']);if(can(p,'AUDIT_VIEW'))nav.push(['audit','audit','Audit trail']);
 return <div className="shell"><aside className="sidebar"><Brand inside/><div className="workspace-label">YOUR WORKSPACE</div><nav>{nav.map(([r,i,n])=><a key={r} href={'#'+r} className={resolved===r?'active':''}><Icon name={i}/>{n}</a>)}</nav><div className="sidebar-bottom"><div className="secure"><Icon/><div>Verified session<small>Password + MFA complete</small></div><i/></div><div className="profile"><span className="avatar">{p.name.slice(0,2).toUpperCase()}</span><div><strong>{p.name}</strong><small>{p.roles.map(r=>r.name).join(' · ')}</small></div></div></div></aside><div className="workspace"><header className="topbar"><span>Workspace <b>/</b> {nav.find(n=>n[0]===resolved)?.[2]||'Overview'}</span><div><span className="dot"/> PAM Backend <button className="text-button" onClick={()=>{setSession(null);setChallenge(null);go('login')}}>Sign out</button></div></header><main><Notice message={flash}/>{resolved==='dashboard'?<Dashboard profile={p}/>:Object.keys(apps).map(n=>n.toLowerCase()).includes(resolved)?<Module key={resolved} name={resolved.toUpperCase()} profile={p} api={api}/>:resolved==='admin'&&canAdmin(p)?<AdminHome profile={p}/>:resolved==='users'&&canAdmin(p)?<Users api={api} currentId={p.id} refresh={refresh}/>:resolved==='roles'&&canAdmin(p)?<Roles api={api} refresh={refresh}/>:resolved==='audit'&&can(p,'AUDIT_VIEW')?<Audit api={api}/>:<div className="empty"><h2>This page is not available</h2><p>Your permissions determine the workspaces you can open.</p><a className="button" href="#dashboard">Back to overview</a></div>}</main><footer className="workspace-footer"><span>SafeAccess / PAM Backend</span><span>Centralized identity. Explicit permissions.</span></footer></div></div>;
}
function Landing(){return <main className="landing"><div className="hero"><section><Badge>LIGHTWEIGHT IDENTITY & ACCESS MANAGEMENT</Badge><h1>Every application.<br/>One secure<br/><em>way in.</em></h1><p>Sign in once. Verify it’s you. Access the applications you’re trusted to use — with every decision accounted for.</p><div className="hero-actions"><a className="button" href="#login">Open your workspace <Icon name="arrow"/></a><a href="#register">Create an account ↗</a></div><div className="proof"><span><Icon name="check"/> Multi-factor authentication</span><span><Icon name="check"/> Fine-grained permissions</span></div></section><div className="identity-visual"><div className="visual-top"><span className="dot"/> CENTRAL ACCESS GATEWAY <span>01</span></div><div className="identity-core"><div className="halo"><Icon/></div><h2>SafeAccess</h2><p>Your verified identity</p><Badge>IDENTITY VERIFIED</Badge></div><div className="connector"/><div className="visual-apps">{Object.entries(apps).map(([key,a])=><div key={key}><Icon name={a.icon}/><span>{key}</span><i/></div>)}</div><div className="visual-foot"><Icon name="audit"/> Every access decision leaves a trace.</div></div></div><div className="features">{[['01','Verify identity','A password starts the process. A one-time code completes it.'],['02','Grant the right access','Roles and permissions determine which applications and actions are available.'],['03','Keep a clear record','Successful and denied access decisions are recorded for review.']].map(([n,t,d])=><article key={n}><span>{n}</span><h3>{t}</h3><p>{d}</p></article>)}</div></main>}
function Auth({route,api,challenge,setChallenge,go,verified,flash}){
 const [error,setError]=useState(''),[busy,setBusy]=useState(false),[info,setInfo]=useState(''),[wait,setWait]=useState(0);const register=route==='register',mfa=route==='mfa';
 useEffect(()=>{if(mfa&&!challenge)go('login')},[mfa,challenge]);useEffect(()=>{if(wait>0){const t=setTimeout(()=>setWait(wait-1),1000);return()=>clearTimeout(t)}},[wait]);
 async function submit(e){e.preventDefault();setBusy(true);setError('');const body=Object.fromEntries(new FormData(e.currentTarget));try{if(register){await api('/auth/register',{method:'POST',body});go('login');}else if(mfa){await verified(await api('/auth/verify-otp',{method:'POST',body:{email:challenge.email,challengeToken:challenge.token,otp:body.otp}}));}else{const r=await api('/auth/login',{method:'POST',body});setChallenge({email:body.email,token:r.challengeToken});go('mfa');}}catch(e){setError(e.message)}finally{setBusy(false)}}
 async function resend(){setBusy(true);setError('');try{const r=await api('/auth/send-otp',{method:'POST',body:{email:challenge.email,challengeToken:challenge.token}});setChallenge({...challenge,token:r.challengeToken});setInfo('New code sent. The previous code is no longer valid.');setWait(30)}catch(e){setError(e.message)}finally{setBusy(false)}}
 return <section className="auth-panel"><span className="eyebrow">{mfa?'STEP 02 / VERIFY':register?'GET STARTED':'WELCOME BACK'}</span><h2>{mfa?'One more step.':register?'Create your identity.':'Sign in to SafeAccess.'}</h2><p>{mfa?'Enter the six-digit code for '+challenge?.email:register?'Your account starts with Employee access.':'Your applications are waiting on the other side.'}</p><Notice message={error||flash}/>{info&&<div className="info">{info}</div>}<form onSubmit={submit}>{register&&<Field label="Full name" name="name" required maxLength="100" autoComplete="name" placeholder="Your full name"/>}{!mfa&&<><Field label="Email address" name="email" type="email" required maxLength="150" autoComplete="email" placeholder="you@example.com"/><Field label="Password" name="password" type="password" required minLength={register?10:undefined} maxLength="72" autoComplete={register?'new-password':'current-password'} placeholder={register?'At least 10 characters':'Enter your password'}/></>}{mfa&&<Field label="Verification code" name="otp" className="otp" required pattern="[0-9]{6}" inputMode="numeric" maxLength="6" autoComplete="one-time-code" placeholder="000000"/>}<button className="button full" disabled={busy}>{busy?'Please wait…':mfa?'Verify & continue':register?'Create account':'Continue securely'}<Icon name="arrow"/></button></form>{mfa?<><p className="note">For this local demo, find the code in the PAM Backend console. Codes expire after five minutes.</p><button className="text-button" disabled={busy||wait>0} onClick={resend}>{wait?'Resend in '+wait+'s':'Send a new code'}</button><a className="text-button" href="#login">Start again</a></>:<p className="note">{register?'Already have an account?':'New to SafeAccess?'} <a href={register?'#login':'#register'}>{register?'Sign in':'Create an account'}</a></p>}<div className="auth-trust"><Icon/> This tab keeps your session in memory. Refreshing signs you out.</div></section>;
}
function Dashboard({profile:p}){const permitted=allowedApps(p);return <><Heading title={'Welcome back, '+p.name.split(' ')[0]+'.'} description="Your identity is verified. Here’s where you can go next." action={<Badge><Icon name="check"/> MFA VERIFIED</Badge>}/><div className="stats">{[['Available applications',permitted.length,'Ready with your current permissions'],['Assigned roles',p.roles.length,p.roles.map(r=>r.name).join(' · ')],['Effective permissions',p.permissions.length,'Combined across all your roles']].map(([t,n,d])=><div key={t}><span>{t}</span><strong>{String(n).padStart(2,'0')}</strong><small>{d}</small></div>)}</div><div className="section-title"><h2>Your applications</h2><span>ONE SIGN-IN. CENTRAL ACCESS.</span></div><div className="app-grid">{permitted.map(a=><AppCard key={a.id} route={a.name.toLowerCase()} title={apps[a.name]?.name||a.name} description={apps[a.name]?.description} icon={apps[a.name]?.icon} badge="AUTHORIZED"/>)}</div>{!permitted.length&&<div className="empty">No applications assigned yet. Contact your administrator.</div>}<div className="details"><section className="panel"><div className="section-title"><h2>Your access profile</h2><Icon name="key"/></div><p>Permissions are checked by PAM Backend on every protected request.</p><div className="chips">{p.permissions.map(v=><span key={v}>{v}</span>)}</div></section><section className="security-panel"><Icon/><h2>Verified, then authorized.</h2><p>Completing MFA proves your identity. Your assigned permissions decide what you can do next.</p><div><span className="dot"/> Current session protected by MFA</div></section></div></>}
function AppCard({route,title,description,icon,badge}){return <a className={'app-card '+route} href={'#'+route}><div className="card-top"><span className="app-icon"><Icon name={icon}/></span>{badge&&<Badge tone="neutral">{badge}</Badge>}</div><h3>{title}</h3><p>{description}</p><div className="card-bottom">Open {title?.toLowerCase()}<Icon name="arrow"/></div></a>}
function Module({name,profile:p,api}){const state=useData(api,'/'+name.toLowerCase());const [error,setError]=useState(''),[result,setResult]=useState(''),[busy,setBusy]=useState(false);async function action(){setBusy(true);setError('');try{setResult((await api('/'+name.toLowerCase(),{method:'POST',body:{}})).message)}catch(e){setError(e.message)}finally{setBusy(false)}}return <><Heading eyebrow="CONNECTED APPLICATION" title={apps[name].name} description="Centralized sign-in. Application-specific permissions."/><Notice message={state.error||error}/>{state.busy?<Loading/>:state.data&&<div className="module-layout"><section className="panel"><Badge>ACCESS GRANTED</Badge><h2 className="module-title">You’re in the {apps[name].name} workspace.</h2><p>{state.data.message}. This demo shows how SafeAccess controls application access.</p><div className="permission-check"><Icon name="check"/><div><strong>{name}_VIEW</strong><small>Verified by PAM Backend for this request</small></div></div><div className="module-action"><h3>Management action</h3><p>Run a demo action to verify {name}_MANAGE. Its outcome is recorded in the audit trail.</p>{!can(p,name+'_MANAGE')&&<p><Badge tone="orange">VIEW-ONLY ACCESS</Badge></p>}<button className={'button '+(!can(p,name+'_MANAGE')?'secondary':'')} disabled={busy} onClick={action}>{busy?'Checking…':can(p,name+'_MANAGE')?'Run management action':'Test restricted action'}</button>{!can(p,name+'_MANAGE')&&<p className="note">Expected result: access denied. This demonstrates server-side enforcement.</p>}{result&&<div className="info" role="status">{result}</div>}</div></section><aside className="panel"><span className="eyebrow">ACCESS DETAILS</span><h3>Your identity travels with you.</h3><dl><dt>Signed in as</dt><dd>{p.email}</dd><dt>Authentication</dt><dd>Password + MFA</dd><dt>Application</dt><dd>{name}</dd><dt>Management permission</dt><dd>{can(p,name+'_MANAGE')?'Granted':'Not assigned'}</dd></dl></aside></div>}</>}
function AdminHome({profile}){return <><Heading eyebrow="ADMINISTRATION" title="Manage trusted access." description="Keep identities, roles, and access decisions in one place."/><div className="app-grid"><AppCard route="users" icon="people" title="Users" description="Create accounts, assign roles, and manage account status."/><AppCard route="roles" icon="key" title="Roles & permissions" description="Build permission sets that define application access."/>{can(profile,'AUDIT_VIEW')&&<AppCard route="audit" icon="audit" title="Audit trail" description="Review successful and denied access decisions."/>}</div></>}
function Users({api,currentId,refresh}){
 const list=useData(api,'/admin/users'),roles=useData(api,'/admin/roles');const [editing,setEditing]=useState(null),[selected,setSelected]=useState([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[query,setQuery]=useState('');
 function edit(u){setEditing(u);setSelected(u.roles?.map(r=>r.id)||[]);setError('');}
 async function save(e){e.preventDefault();setBusy(true);setError('');const body=Object.fromEntries(new FormData(e.currentTarget));if(!body.password)delete body.password;body.roleIds=selected;try{await api('/admin/users'+(editing.id?'/'+editing.id:''),{method:editing.id?'PUT':'POST',body});setEditing(null);await list.load();await refresh()}catch(e){setError(e.message)}finally{setBusy(false)}}
 async function deactivate(u){if(!confirm('Deactivate '+u.name+'? Their history will be retained.'))return;setBusy(true);setError('');try{await api('/admin/users/'+u.id,{method:'DELETE'});await list.load()}catch(e){setError(e.message)}finally{setBusy(false)}}
 const shown=(list.data||[]).filter(u=>(u.name+' '+u.email).toLowerCase().includes(query.toLowerCase()));
 return <><Heading eyebrow="ADMINISTRATION" title="User management" description="The right roles for every identity." action={<button className="button" onClick={()=>edit({status:'ACTIVE'})}>+ Create user</button>}/><Notice message={list.error||roles.error||error}/>{editing&&<section className="panel editor"><div className="section-title"><h2>{editing.id?'Edit identity':'Create identity'}</h2><button className="text-button" onClick={()=>setEditing(null)}>Cancel</button></div><form onSubmit={save} key={editing.id||'new'}><div className="form-grid"><Field label="Full name" name="name" defaultValue={editing.name||''} required maxLength="100"/><Field label="Email" name="email" type="email" defaultValue={editing.email||''} required maxLength="150"/><Field label={editing.id?'New password (optional)':'Initial password'} name="password" type="password" required={!editing.id} minLength="10" maxLength="72" autoComplete="new-password"/><label className="field"><span>Status</span><select name="status" defaultValue={editing.status||'ACTIVE'}><option>ACTIVE</option><option>INACTIVE</option></select></label></div><span className="eyebrow">ASSIGNED ROLES</span><div className="checkboxes">{roles.data?.map(r=><label key={r.id}><input type="checkbox" checked={selected.includes(r.id)} onChange={e=>setSelected(e.target.checked?[...selected,r.id]:selected.filter(x=>x!==r.id))}/>{r.name}</label>)}</div><button className="button" disabled={busy||!selected.length}>{busy?'Saving…':'Save user'}</button></form></section>}<section className="panel table-panel"><div className="table-toolbar"><h2>All identities <Badge tone="neutral">{list.data?.length||0}</Badge></h2><input aria-label="Search users" placeholder="Search name or email…" value={query} onChange={e=>setQuery(e.target.value)}/></div>{list.busy?<Loading/>:<div className="table-scroll"><table><thead><tr><th>Identity</th><th>Roles</th><th>Status</th><th>Actions</th></tr></thead><tbody>{shown.map(u=><tr key={u.id}><td><strong>{u.name}</strong><small>{u.email}</small></td><td>{u.roles.map(r=><Badge key={r.id} tone="neutral">{r.name}</Badge>)}</td><td><Badge tone={u.status==='ACTIVE'?'':'orange'}>{u.status}</Badge></td><td><button className="text-button" onClick={()=>edit(u)}>Edit</button>{u.id!==currentId&&u.status==='ACTIVE'&&<button className="text-button danger" disabled={busy} onClick={()=>deactivate(u)}>Deactivate</button>}</td></tr>)}</tbody></table>{!shown.length&&<div className="empty">No users match your search.</div>}</div>}</section></>
}
function Roles({api,refresh}){
 const list=useData(api,'/admin/roles'),catalog=useData(api,'/permissions');const [editing,setEditing]=useState(null),[selected,setSelected]=useState([]),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 function edit(r){setEditing(r);setSelected(r.permissionIds||[]);setError('');}
 async function save(e){e.preventDefault();setBusy(true);setError('');const name=new FormData(e.currentTarget).get('name');try{await api('/admin/roles'+(editing.id?'/'+editing.id:''),{method:editing.id?'PUT':'POST',body:{name,permissionIds:selected}});setEditing(null);await list.load();await refresh()}catch(e){setError(e.message)}finally{setBusy(false)}}
 return <><Heading eyebrow="ADMINISTRATION" title="Roles & permissions" description="Define access once. Assign it to the right people." action={<button className="button" onClick={()=>edit({})}>+ Create role</button>}/><Notice message={list.error||catalog.error||error}/>{editing&&<section className="panel editor"><div className="section-title"><h2>{editing.id?'Edit role':'Create role'}</h2><button className="text-button" onClick={()=>setEditing(null)}>Cancel</button></div><form onSubmit={save}><Field key={editing.id||'new'} label="Role name" name="name" defaultValue={editing.name||''} pattern="[A-Z][A-Z0-9_]{1,49}" required placeholder="e.g. AUDITOR"/><div className="checkboxes">{catalog.data?.map(p=><label key={p.id}><input type="checkbox" checked={selected.includes(p.id)} onChange={e=>setSelected(e.target.checked?[...selected,p.id]:selected.filter(x=>x!==p.id))}/>{p.name}</label>)}</div><button className="button" disabled={busy}>{busy?'Saving…':'Save role'}</button></form></section>}{list.busy?<Loading/>:<div className="role-grid">{list.data?.map(r=><section className="panel role-card" key={r.id}><div className="section-title"><span className="app-icon"><Icon name="key"/></span><Badge tone="neutral">{r.permissions.length} PERMISSIONS</Badge></div><h2>{r.name}</h2><div className="chips">{r.permissions.map(p=><span key={p.id}>{p.name}</span>)}</div>{r.name==='ADMIN'?<p className="note">Built-in administrator permissions are protected.</p>:<button className="text-button" onClick={()=>edit(r)}>Edit permissions →</button>}</section>)}</div>}</>
}
function Audit({api}){const [page,setPage]=useState(0),state=useData(api,'/audit?page='+page+'&size=20');return <><Heading eyebrow="ACCOUNTABILITY" title="Audit trail" description="A clear record of identities, resources, and access decisions." action={<button className="button secondary" onClick={state.load}>Refresh log</button>}/><Notice message={state.error}/><section className="panel table-panel"><div className="table-toolbar"><h2>Recorded events</h2><Badge tone="neutral">{state.data?.totalElements||0} TOTAL</Badge></div>{state.busy?<Loading/>:<div className="table-scroll"><table><thead><tr><th>Result</th><th>Action</th><th>Resource</th><th>User</th><th>Timestamp</th></tr></thead><tbody>{state.data?.content.map(e=><tr key={e.id}><td><Badge tone={e.status==='SUCCESS'?'':'orange'}>{e.status}</Badge></td><td><code>{e.action}</code></td><td>{e.resource}</td><td>{e.userId?'#'+e.userId:'Unknown identity'}</td><td className="nowrap">{new Date(e.createdAt).toLocaleString()}</td></tr>)}</tbody></table>{!state.data?.content.length&&<div className="empty">No audit events recorded yet.</div>}</div>}<div className="pagination"><span>Page {page+1} of {Math.max(1,state.data?.totalPages||1)}</span><div><button className="button secondary small" disabled={!page||state.busy} onClick={()=>setPage(page-1)}>Previous</button><button className="button secondary small" disabled={state.busy||page+1>=(state.data?.totalPages||0)} onClick={()=>setPage(page+1)}>Next</button></div></div></section></>}
createRoot(document.getElementById('root')).render(<App/>);
