CREATE TABLE IF NOT EXISTS users(id BIGINT AUTO_INCREMENT PRIMARY KEY,name VARCHAR(100) NOT NULL,email VARCHAR(150) UNIQUE NOT NULL,password_hash VARCHAR(255) NOT NULL,status VARCHAR(20) NOT NULL,created_at TIMESTAMP);
CREATE TABLE IF NOT EXISTS roles(id BIGINT AUTO_INCREMENT PRIMARY KEY,name VARCHAR(50) UNIQUE NOT NULL);
CREATE TABLE IF NOT EXISTS permissions(id BIGINT AUTO_INCREMENT PRIMARY KEY,name VARCHAR(100) UNIQUE NOT NULL);
CREATE TABLE IF NOT EXISTS user_roles(user_id BIGINT REFERENCES users(id),role_id BIGINT REFERENCES roles(id),PRIMARY KEY(user_id,role_id));
CREATE TABLE IF NOT EXISTS role_permissions(role_id BIGINT REFERENCES roles(id),permission_id BIGINT REFERENCES permissions(id),PRIMARY KEY(role_id,permission_id));
CREATE TABLE IF NOT EXISTS applications(id BIGINT AUTO_INCREMENT PRIMARY KEY,name VARCHAR(100) UNIQUE NOT NULL,description VARCHAR(255));
CREATE TABLE IF NOT EXISTS permission_applications(permission_id BIGINT REFERENCES permissions(id),application_id BIGINT REFERENCES applications(id),PRIMARY KEY(permission_id,application_id));
CREATE TABLE IF NOT EXISTS mfa_codes(id BIGINT AUTO_INCREMENT PRIMARY KEY,user_id BIGINT NOT NULL REFERENCES users(id),code VARCHAR(255) NOT NULL,expires_at TIMESTAMP NOT NULL,used BOOLEAN DEFAULT FALSE,attempt_count INT DEFAULT 0 NOT NULL);
CREATE TABLE IF NOT EXISTS audit_logs(id BIGINT AUTO_INCREMENT PRIMARY KEY,user_id BIGINT REFERENCES users(id),action VARCHAR(100) NOT NULL,application VARCHAR(100),status VARCHAR(20) NOT NULL,ip_address VARCHAR(45),created_at TIMESTAMP);
